# 异常

```
try{
   ...
   throw("abc");
}
catch(err){

    if(err=="abc"){
    }
}

Throw抛出的异常参数，由err变量接收
```
